name: Build BurritoSpigot

on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
            matrix:
                java: [8, 17]
            fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java}}
        distribution: 'temurin'
    - name: Cache maven
      uses: actions/cache@v2
      with:
        path: |
            ~/.m2/repository/
            work/1.8.8
        key: ${{ runner.os }}-burrito-2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-paper-2
    - name: Patch and Build
      run: cd BurritoSpigot-Server && ./burrito build
    - uses: actions/upload-artifact@v2
      with:
        name: BurritoSpigot JDK ${{ matrix.java }}
        path: ./BurritoSpigot-Server/target/BurritoSpigot.jar
    - name: Push artifact to downloads
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      if: ${{ matrix.java == 8 && github.event_name != 'pull_request' && github.repository == 'CobbleSword/BurritoSpigot' && github.ref == 'refs/heads/main' }}
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'BurritoSpigot-Server/target/BurritoSpigot.jar'
        destination_repo: 'CobbleSword/BurritoSpigot'
        destination_folder: 'jars'
        destination_branch: 'downloads'
        user_email: 'action@github.com'
        user_name: 'Github Actions'
        commit_message: Update downloads for commit ${{ github.sha }}
