name: Build BurritoSpigot

on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
            matrix:
                java: [8, 11, 17]
            fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java}}
        distribution: 'temurin'
        cache: maven
    - name: Patch and Build
      run: cd BurritoSpigot-Server && ./burrito build
    - uses: actions/upload-artifact@v2
      if: ${{ matrix.java == 8 && github.event_name != 'pull_request' }}
      with:
        name: BurritoSpigot
        path: ./BurritoSpigot-Server/target/BurritoSpigot.jar
