name: Build BurritoSpigot

on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
            matrix:
                java: [17]
            fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java}}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd BurritoSpigot-Server && ./burrito build
    - uses: actions/upload-artifact@v2
      if: ${{ matrix.java == 8 }}
      with:
        name: BurritoSpigot
        path: ./BurritoSpigot-Server/target/BurritoSpigot.jar
        
    - name: Create Release Draft
      if: ${{ github.event_name != 'pull_request' }}
      id: createDraft
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: BurritoSpigot-${{ github.sha }}
        release_name: BurritoSpigot ${{ github.sha }}
        body: BurritoSpigot Update
        draft: false
    - name: Upload Release Asset
      if: ${{ github.event_name != 'pull_request' }}
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createDraft.outputs.upload_url }}
        asset_path: ./BurritoSpigot-Server/target/BurritoSpigot.jar
        asset_name: BurritoSpigot.jar
        asset_content_type: application/java-archive
